### ISSUE TITLE
All CPU/Memory settings are required in UI

### ISSUE THREAD

**Issue by kravciak** [kubewarden/container-resources-policy#10]
Readme says: `...at least one of the configurations, cpu, or memory should be defined including all their sub fields.`

When I fill only one of CPU / Memory settings then generated yaml is following:
```yaml
  settings:
    description: null
    cpu:
      defaultRequest: 100M
      defaultLimit: 100M
      maxLimit: 100M
    memory:
      defaultRequest: ''
      defaultLimit: ''
      maxLimit: ''
```

This produces error `"Provided settings are not valid: invalid memory settings\nall the quantities must be defined"`

Kubernetes shows this policy (in pending state):
```yaml
# k get clusteradmissionpolicies.policies.kubewarden.io cr -o yaml
   ...
  settings:
    cpu:
      defaultLimit: 100m
      defaultRequest: 100m
      maxLimit: 100m
    memory: {}
```

**Comment by flavio** [comment]
@jvanz can you please take a look into that?

**Comment by jvanz** [comment]
@kravciak as far as I can see in the code, this is right. The code enforce that when you define the `memory` field, all the subfields must be defined. And the `''` value is not consider valid. If you do not want to enforce memory validation, you must remove the `memory` field in the settings. 

Can you test removing the whole `memory` object and test again?

**Comment by jvanz** [comment]
I've had a quick chat with @kravciak and I understand the problem. The issue is related on how the settings are shown in the Rancher UI. In the rancher UI, in the current state, it's not possible to leave the fields (`cpu` or `memory`) out of the settings. They will always be present with the empty sub fields. Witch is causing the problem.  

I'm try to see if I can change the `questions-ui.yml` file to solve this problem.

**Comment by jvanz** [comment]
@jordojordo I think we need to handle this in the UI. I've created a new [container resource policy](https://artifacthub.io/packages/kubewarden/jvanz-container-resource-policy/container-resources) and change the `questions-ui.yml` to use `null` as the default values for the `CPU` and `Memory` settings in the `questions-ui.yml`. 

When I load the policies view in the Rancher UI, in request sent to the backend,  I can see that the policy loaded is using the latest questions files:

```yaml
questions:
- default: null
  description: >-
    This policy is designed to enforce constraints on the resource requirements
    of Kubernetes containers.
  group: Settings
  label: Description
  required: false
  hide_input: true
  type: string
  variable: description
- default: null
  description: Defines the limit and minimum amount requested for CPU resource
  group: Settings
  label: CPU
  hide_input: true
  type: map[
  variable: cpu
  subquestions:
    - default: ''
      tooltip: >-
        Defines default minimum CPU requested.
      group: Settings
      label: Default CPU requested
      type: string
      variable: cpu.defaultRequest
    - default: ''
      tooltip: >-
        Defines default CPU limit value.
      group: Settings
      label: Default CPU limit
      type: string
      variable: cpu.defaultLimit
    - default: ''
      tooltip: >-
        Defines maximum limit value allowed to be set for the CPU resource
      group: Settings
      label: Max CPU limit allowed
      type: string
      variable: cpu.maxLimit
- default: null
  description: Defines the limit and minimum amount requested for memory resource
  group: Settings
  label: Memory
  hide_input: true
  type: map[
  variable: memory
  subquestions:
    - default: ''
      tooltip: >-
        Defines default minimum memory requested.
      group: Settings
      label: Default memory requested
      type: string
      variable: memory.defaultRequest
    - default: ''
      tooltip: >-
        Defines default memory limit value.
      group: Settings
      label: Default memory limit
      type: string
      variable: memory.defaultLimit
    - default: ''
      tooltip: >-
        Defines maximum limit value allowed to be set for the memory resource
      group: Settings
      label: Max memory limit allowed
      type: string
      variable: memory.maxLimit
- default: []
  description: >-
    Configuration used to exclude containers from enforcement
  group: Settings
  label: Ignore images
  type: array[
  value_multiline: false
  variable: ignoreImages
```

However, when I've create the policy, the empty fields are still being sent to the backend. Which lead to the problem where the memory field has its subfields with empty strings. Which is the root cause of this problem. This is the POST data when I do not define any CPU or Memory configuration

```json
{
  "type": "policies.kubewarden.io.clusteradmissionpolicy",
  "metadata": {
    "annotations": {
      "artifacthub/pkg": "container-resources/container-resources/0.1.0"
    },
    "name": "container-resrouce"
  },
  "apiVersion": "policies.kubewarden.io.v1",
  "kind": "ClusterAdmissionPolicy",
  "spec": {
    "policyServer": "default",
    "module": "ghcr.io/kubewarden/policies/container-resources:v0.1.0",
    "rules": [
      {
        "apiGroups": [
          null
        ],
        "apiVersions": [
          "v1"
        ],
        "resources": [
          "pods"
        ],
        "operations": [
          "CREATE"
        ]
      },
      {
        "apiGroups": [
          null
        ],
        "apiVersions": [
          "v1"
        ],
        "resources": [
          "replicationcontrollers"
        ],
        "operations": [
          "CREATE",
          "UPDATE"
        ]
      },
      {
        "apiGroups": [
          "apps"
        ],
        "apiVersions": [
          "v1"
        ],
        "resources": [
          "deployments",
          "replicasets",
          "statefulsets",
          "daemonsets"
        ],
        "operations": [
          "CREATE",
          "UPDATE"
        ]
      },
      {
        "apiGroups": [
          "batch"
        ],
        "apiVersions": [
          "v1"
        ],
        "resources": [
          "jobs",
          "cronjobs"
        ],
        "operations": [
          "CREATE",
          "UPDATE"
        ]
      }
    ],
    "mutating": true,
    "settings": {
      "cpu": {},
      "memory": {}
    },
    "mode": "protect",
    "namespaceSelector": {
      "matchExpressions": [
        {
          "key": "kubernetes.io/metadata.name",
          "operator": "NotIn",
          "values": [
            "calico-system",
            "cattle-alerting",
            "cattle-fleet-local-system",
            "cattle-fleet-system",
            "cattle-global-data",
            "cattle-global-nt",
            "cattle-impersonation-system",
            "cattle-istio",
            "cattle-logging",
            "cattle-pipeline",
            "cattle-prometheus",
            "cattle-system",
            "cert-manager",
            "ingress-nginx",
            "kube-node-lease",
            "kube-public",
            "kube-system",
            "rancher-operator-system",
            "security-scan",
            "tigera-operator"
          ]
        }
      ]
    }
  }
}
``` 

The settings should not contains the `cpu` and `memory` field if the user does not define all its subfields in the UI.

Can you help us on that?
