### ISSUE TITLE
Cannot Deploy with empty Memory settings

### ISSUE THREAD

**Issue by TechDufus** [kubewarden/container-resources-policy#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deploying with the following settings via the UI:
```yaml
settings:
    cpu:
      defaultLimit: 500m
      defaultRequest: 50m
      maxLimit: 2000m
    memory: {}
```
![image](https://github.com/kubewarden/container-resources-policy/assets/46715299/7e4b0db9-7dc8-4613-952a-7c93e3276491)

I get this error from the new policy server trying to spin up:
```
policy-server-default Error: [clusterwide-max-requests-limits] settings are not valid: Some("Provided settings are not valid: invalid memory settings all the quantities must be defined")
```

### Expected Behavior

I should be able to ONLY set CPU settings via the Rancher / Kubewarden UI and have the policy server successfully redeploy.

### Steps To Reproduce

Steps provided above.

### Environment

```markdown
Versions:
- Rancher: 2.8.2
- K8s: v1.25.16+rke2r1
- Kubewarden App Version: v1.11.0
- Kubewarden Rancher Extension: 1.4.0
```

**Comment by viccuad** [comment]
As a workaround, you can click on "edit YAML", and remove the empty `settings.memory` key.

**Comment by viccuad** [comment]
This would be a good moment to revisit questions-ui.yml and add support for `settings.memory.ignoreValues` and `settings.cpu.ignoreValues`.

**Comment by kravciak** [comment]
Hi, pls how did you generate YAML in your description? There was [a bug](https://github.com/kubewarden/container-resources-policy/issues/10) in previous UI versions, but it was fixed.
When I create policy in UI extension v1.4.0 and switch to Edit YAML tab, I get this:

```yaml
  # Filled only CPU values in policy settings tab
  settings:
    cpu:
      defaultRequest: '100'
      defaultLimit: '100'
      maxLimit: '100'
    memory:
      defaultRequest: ''
      defaultLimit: ''
      maxLimit: ''
```

I can't reproduce getting `memory: {}` in YAML from UI 1.4.0.
